name = "Juniper"
uuid = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
repo = "https://github.com/lanl-ansi/Juniper.jl.git"
authors = ["Ole Kr√∂ger <o.kroeger@wikunia.de>", "Kaarthik Sundar kaarthik@lanl.gov"]
version = "0.4.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
JSON = ">= 0.18.0"
JuMP = "^0.19.0"
MathOptInterface = "^0.8.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["Test", "Cbc", "Ipopt", "Logging"]